import { ROLE_GROUPS } from "@/core/permissions/roles";

export const CTPAT_PERMISSIONS = {
  CREATE: ROLE_GROUPS.CALIDAD,
  EDIT_STEPS: ROLE_GROUPS.CALIDAD,
  VIEW_DOCUMENTS: ROLE_GROUPS.CALIDAD_Y_EXPORTACIONES,
  EDIT_PACKING_ITEMS: ROLE_GROUPS.CALIDAD,
} as const;
